version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fuelphp-app
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html/my_fuel_project
    networks:
      - fuelphp-network

  db:
    build:
      context: ../
      dockerfile: docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: profile_archive_system_db
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fuelphp-network

networks:
  fuelphp-network:
    driver: bridge
